name: Apply Version Metadata

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Auto Apply Version Metadata
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply version metadata
      run: |
        python test/auto_apply_version_metadata.py
