name: MetaDataCheck

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check MetaData
      run: |
        echo "Analyzing All Py Files"
        for pyfile in $(git ls-files '*.py'); do
          cat $pyfile | grep "# ba_meta require api 7" > /dev/null || (echo "$pyfile doesn't have the MetaData present in it." && exit 1)
        done
        echo "All Py Files have MetaData present in them."
