name: PluginCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install jq
    - name: Analysing mods
      run: |
        for jsonfile in $(git ls-files '*.json'); do
          echo "Analyzing $jsonfile"
          jq -e < $jsonfile > /dev/null || exit 1;
        done
